name: basis_data
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.2.1
  google_fonts: ^6.2.1 # Added Google Fonts package
  flutter_secure_storage: ^9.0.0 # Ditambahkan untuk menyimpan token dengan aman
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.2.3 
  permission_handler: ^11.3.1
  image_picker: ^1.2.1
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/logo2.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"

flutter:
  uses-material-design: true
